# This action is used to set up the environment for each OS

name: 'Set up environement'
description: 'Configures environment variables, Flutter and Xcode'
runs:
  using: "composite"
  steps:
    - name: Set global environment variables
      uses: ./.github/actions/setvars
      with:
        varFilePath: ./.github/variables/global.env
    
    - name: Set up Xcode
      if: os == macos # todo: fix
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    
